# Generated by Django 5.0.4 on 2024-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='post',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_number',
            field=models.CharField(default='No contact number provided', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='No address provided', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='post',
            name='qualifications',
            field=models.TextField(default='No adderss provided'),
        ),
        migrations.AddField(
            model_name='post',
            name='subjects_teaching',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
