# Generated by Django 5.0.4 on 2024-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
