# Generated by Django 5.0.4 on 2024-06-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0005_rename_post_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects_teaching',
        ),
        migrations.RemoveField(
            model_name='student',
            name='years_of_experience',
        ),
    ]
